apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: venkat345/backend-service1
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent # or Always

