version: '3.8'

services:
  backend:
    build:
      context: ./Demo  # Path to your FastAPI backend folder
      dockerfile: Dockerfile
    container_name: final-bakcend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app.db
    restart: always

  frontend:
    build:
      context: ./project # Path to your React Vite frontend folder
      dockerfile: Dockerfile
    container_name: final-frontend
    ports:
      - "5174:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
