apiVersion: v1
kind: Service
metadata:
  name: ram-frontend-service
spec:
  selector:
    app: frontend56
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
  type: {{ .Values.frontend.service.type }}
