apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-helm
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend56
  template:
    metadata:
      labels:
        app: frontend56
    spec:
      containers:
      - name: frontend56
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: 80
