apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
      - name: frontend2
        image: venkat345/frontend-demo21:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent # or Always
