apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
      - image: venkat345/frontend-demo12:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent # or Always
