apiVersion: v1
kind: Service
metadata:
  name: frontend-demo34
spec:
  type: LoadBalancer
  selector:
    app: frontend2
  ports:
    - protocol: TCP
      port: 81          # Change this to 81
      targetPort: 80    # This should match the container's port
