apiVersion: v1
kind: Service
metadata:
  name: frontend-demo36
spec:
  type: LoadBalancer
  selector:
    app: frontend3
  ports:
    - protocol: TCP
      port: 80           # Change this to 80
      targetPort: 80     # Ensure your container is also exposing this port
