backend:
  image: 
    repository: venkat345/backend-service1
    tag: latest
  service:
    type: LoadBalancer
  
    port: 8000
  replicas: 2

frontend:
  image: 
    repository: venkat345/googleaut-frontend
    tag: latest          
  service:
    type: LoadBalancer
    port: 80
  replicas: 2

serviceAccount:
  create: false

ingress:
  enabled: false
autoscaling:
  enabled: false
