name: CI/CD with Helm for AKS

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend Image
        run: |
          cd Demo  # Navigate to backend directory
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend12:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend12:latest

      - name: Build & Push Frontend Image
        run: |
          cd Frontend  # Navigate to frontend directory
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-demo23:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-demo23:latest

  deploy-to-aks:
    name: Deploy to AKS using Helm
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AKS_CLUSTER }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

     
      - name: Deploy Backend & Frontend using Helm (`myapp-chart1`)
        run: |
          helm upgrade --install my-app ./myapp-chart1 --force

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Deployment failed. Rolling back..."
          helm rollback myapp-release || echo "No previous revision found."
